#!/bin/bash

killall -9 -q sxhkd
sxhkd &

killall -9 -q redshift
redshift -x                   # reset mode
redshift -c ~/.config/redshift.conf &                   # screen light

killall -9 -q dunst
dunst &                          # notification daemon 

killall -9 -q compton                                      # killall previus compton
compton --config ~/.config/compton/compton.conf &       # Transparency Management

killall -9 -q xautolock                                    # killall autolock
xautolock -detectsleep -time 10 \
 -locker "i3lock -fenti ~/.config/lock.png" -notify 60 \
 -notifier "notify-send -u critical -t 20000 -- 'LOCKING screen in 60 seconds'" &        # Automatic screenlock

wmname LG3D &                                           # Fix problem Burp Suite proportion full screen

feh --bg-fill ~/.config/wallpaper.png &                 # Set wallpaper brackground

~/.config/polybar/launch.sh &                           # Launch polybar

bspc config pointer_modifier mod1                       # Set key super to key windows (metawin)
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        5
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true




# http://fontawesome.io/cheatsheet/
# remove all rules first
#bspc rule -r *:*
#bspc rule -a spotify monitor="^1" desktop="^2"

# fullscreen -> super + f
# floating -> super + s
# tiled -> mosaico
# pseudo_tiled -> mosaico que se puede especificar size rectangle=800x800+0+0
bspc rule -a Nm-connection-editor state=floating rectangle=800x800+0+0 follow=on focus=on
bspc rule -a TelegramDesktop state=floating follow=on focus=on
bspc rule -a Yad state=floating follow=on focus=on

## workspace 1 (labs)  
bspc rule -a konsole state=tiled follow=on focus=on
bspc rule -a VirtualBox Manager desktop='^1' follow=on focus=on
bspc rule -a VirtualBox Machine desktop='^1' follow=on focus=on

## workspace 2 (web browsers)  
bspc rule -a Firefox desktop='^2' follow=on focus=on
bspc rule -a Chromium desktop='^2' state=pseudo_tiled follow=on focus=on


## workspace 3 (file-manager)  
bspc rule -a dolphin follow=on focus=on
bspc rule -a Insync state=floating rectangle=500x800+0+20 follow=on focus=on


## workspace 4 (text-editors)  
bspc rule -a Sublime_text follow=on focus=on
bspc rule -a Meld desktop='^4' state=fullscreen follow=on focus=on
bspc rule -a libreoffice desktop='^4' follow=on focus=on
bspc rule -a libreoffice-base desktop='^4' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^4' follow=on focus=on
bspc rule -a libreoffice-draw desktop='^4' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^4' follow=on focus=on
bspc rule -a libreoffice-math desktop='^4' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^4' follow=on focus=on
bspc rule -a libreoffice-startcenter desktop='^4' follow=on focus=on

## workspace 5 (graphic-editors)  
bspc rule -a Gimp desktop='^5' follow=on focus=on
bspc rule -a Inkscape desktop='^5' follow=on focus=on

## workspace 6 (multimedia)  
bspc rule -a vlc desktop='^6' state=fullscreen follow=on focus=on
bspc rule -a Spotify desktop='^6' follow=on


## workspace 7 (code)  
bspc rule -a jetbrains-pycharm desktop='^7' follow=on focus=on


## workspace 8 (system-settings)  
bspc rule -a ksysguard desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
bspc rule -a systemsettings desktop='^8' follow=on focus=on
bspc rule -a Pavucontrol desktop='^8' follow=on focus=on



#       v       





# Other
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


killall -9 -q autorun
~/.config/bspwm/scripts/autorun >> /tmp/bspwm.log &                       # Autorun scripts


notify-send -u normal -t 5000 "bspwm" "bspwm started correctly"
#dunstify -i ~/.config/icons/ok.svg -u normal -t 5000 "bspwm" "bspwm started correctly"

