#! /bin/sh

sxhkd &

compton --config ~/.config/compton/compton.conf &   # Transparency Management
wmname LG3D & 				                        # Fix problem Burp Suite proportion full screen
feh --bg-fill ~/.config/wallpaper.png &             # Set wallpaper brackground
~/.config/polybar/launch.sh &                       # Launch polybar

bspc config pointer_modifier mod1	                # Set key super to key windows (metawin)
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Caja desktop='^8' state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
