#!/bin/bash

killall -9 -q sxhkd
sxhkd &                                             # shortcut

killall -9 -q redshift
redshift -x                                         # reset mode
redshift -c ~/.config/redshift.conf &               # screen light

killall -9 -q dunst
dunst &                                             # notification daemon 

killall -9 -q compton
compton --config ~/.config/compton/compton.conf &   # Transparency Management

killall -9 -q xautolock                                    # killall autolock
xautolock -detectsleep -time 10 \
 -locker "i3lock -fenti ~/.config/lock.png" -notify 60 \
 -notifier "notify-send -u critical -t 20000 -- 'LOCKING screen in 60 seconds'" &        # Automatic screenlock

wmname LG3D &                                       # Fix problem Burp Suite proportion full screen

feh --bg-fill ~/.config/wallpaper.png &             # Set wallpaper brackground

~/.config/polybar/launch.sh &                       # Launch polybar

bspc config pointer_modifier mod1                   # Set key super to key windows (metawin)


if [ "$(cat /etc/hostname)" == "xiaomi" ]; then
    bspc monitor eDP-1 -d I II III IV V VI VII
    bspc monitor HDMI-2 -d VIII IX X
elif [ "$(cat /etc/hostname)" == "4770K" ]; then
    #~/scripts/hdmi.sh l DP-0 HDMI-0 144 60 > /dev/null
    bspc monitor HDMI-0 -d I II III IV V
    bspc monitor DP-0 -d VI VII VIII IX X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width        5
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true




# http://fontawesome.io/cheatsheet/
# remove all rules first
#bspc rule -r *:*
#bspc rule -a spotify monitor="^1" desktop="^2"

# fullscreen -> super + f
# floating -> super + s
# tiled -> mosaico
# pseudo_tiled -> mosaico que se puede especificar size rectangle=800x800+0+0
bspc rule -a Nm-connection-editor state=floating rectangle=800x800+0+0 follow=on focus=on
bspc rule -a TelegramDesktop state=floating follow=on focus=on
bspc rule -a Yad state=floating follow=on focus=on
bspc rule -a Blueberry.py state=floating follow=on focus=on

## workspace 1 (labs)  
bspc rule -a konsole state=tiled follow=on focus=on
bspc rule -a VirtualBox Manager follow=on focus=on
bspc rule -a VirtualBox Machine follow=on focus=on

## workspace 2 (web browsers)  
bspc rule -a Firefox follow=on focus=on
bspc rule -a Chromium state=pseudo_tiled follow=on focus=on


## workspace 3 (file-manager)  
bspc rule -a dolphin follow=on focus=on
bspc rule -a Insync state=floating rectangle=500x800+5+40 follow=on focus=on


## workspace 4 (text-editors)  
bspc rule -a Sublime_text follow=on focus=on
bspc rule -a Meld state=fullscreen follow=on focus=on

## workspace 5 (graphic-editors)  
bspc rule -a Gimp follow=on focus=on
bspc rule -a Inkscape follow=on focus=on

## workspace 6 (multimedia)  
bspc rule -a vlc state=fullscreen follow=on focus=on
bspc rule -a Spotify follow=on


## workspace 7 (code)  
bspc rule -a jetbrains-pycharm follow=on focus=on


## workspace 8 (system-settings)  
bspc rule -a ksysguard follow=on focus=on
bspc rule -a GParted follow=on focus=on
bspc rule -a systemsettings follow=on focus=on
bspc rule -a Pavucontrol follow=on focus=on



#       v       





# Other
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


killall -9 -q autorun
~/.config/bspwm/scripts/autorun >> /tmp/bspwm.log &                       # Autorun scripts


notify-send -u normal -t 5000 "bspwm" "bspwm started correctly"
#dunstify -i ~/.config/icons/ok.svg -u normal -t 5000 "bspwm" "bspwm started correctly"



