version: 2  # https://circleci.com/docs/2.0/adv-config/
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            # find . -type f -name '*.sh' -exec shellcheck -e SC2086 --exclude SC2034 --external-sources {} \;
            shellcheck -e SC2086 --external-sources custom_workspace.sh

workflows:
  version: 2
  check-build:
    jobs:
      - shellcheck:
          filters:
            branches: # only run shellcheck on branchs
              only:
                - main
                - master
                - dev
